chore: HealthCheck discard

diff --git a/nginx_copy/srcs/requirements/nginx/Dockerfile b/nginx_copy/srcs/requirements/nginx/Dockerfile
--- a/nginx_copy/srcs/requirements/nginx/Dockerfile
+++ b/nginx_copy/srcs/requirements/nginx/Dockerfile
@@ -5,11 +5,11 @@ RUN apt-get install curl -y
 RUN apt-get install nginx openssl -y
 
 COPY ./tools/script.sh /
-COPY ./tools/wait-for-it.sh /
 
 RUN chmod +x ./script.sh
-RUN chmod +x ./wait-for-it.sh
 
 CMD [ "./script.sh" ]
 
 EXPOSE 443
+
+# HEALTHCHECK --interval=20s --timeout=20s --retries=20 CMD curl -k -f https://localhost || exit 1
diff --git a/nginx_copy/srcs/requirements/wordpress/Dockerfile b/nginx_copy/srcs/requirements/wordpress/Dockerfile
--- a/nginx_copy/srcs/requirements/wordpress/Dockerfile
+++ b/nginx_copy/srcs/requirements/wordpress/Dockerfile
@@ -8,12 +8,12 @@ RUN apt-get install mariadb-client -y
 RUN apt-get install curl -y
 
 
-COPY ./tools/wait-for-it.sh /wait-for-it.sh
 COPY ./tools/script.sh /script.sh
 
-RUN chmod +x wait-for-it.sh
 RUN chmod +x script.sh
 
 CMD [ "./script.sh" ]
 
 EXPOSE 9000
+
+# HEALTHCHECK --interval=20s --timeout=20s --retries=20 CMD pgrep php-fpm || exit 1
